dataset: ['Movies_and_TV']
batch_size: 1024
split: ['0.8','0.1','0.1']
interval: 1
early_stop: 5
verbose: False
draw_loss_points: 100
L2: 0.0

model: 'EulerNet'
embedding_size: 16
learning_rate: 0.001
weight_decay: 0.00001
depth: 2
mlp: [0, 400, 400, 400, 1]
num_layers: 2
dp_rate: 0.0